// <auto-generated />
using System;
using ArquivoWinchester.Infra.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArquivoWinchester.Infra.Dados.Migrations
{
    [DbContext(typeof(ArquivoWinchesterContexto))]
    partial class ArquivoWinchesterContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArquivoWinchester.Dominio.Entidades.CacadaEntidade.Cacada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CacadorAtualizadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CacadorCriadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCacada")
                        .HasColumnType("datetime2");

                    b.Property<string>("DificuldadeCacada")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Resumo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SerSobrenaturalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusCacada")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("CacadorCriadorId");

                    b.HasIndex("SerSobrenaturalId");

                    b.ToTable("TB_Cacadas", (string)null);
                });

            modelBuilder.Entity("ArquivoWinchester.Dominio.Entidades.CacadorEntidade.Cacador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anotacoes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("EspecialidadeCacador")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NomeCacador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<int>("Papel")
                        .HasColumnType("int");

                    b.Property<string>("RegiaoBaseCacador")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusCacador")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NomeCacador")
                        .IsUnique();

                    b.ToTable("TB_Cacadores", (string)null);
                });

            modelBuilder.Entity("ArquivoWinchester.Dominio.Entidades.SerSobrenaturalEntidade.SerSobrenatural", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CacadorAtualizadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CacadorCriadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contramedida")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NivelRiscoSerSobrenatural")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NomeEntidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SinaisComuns")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StatusSerSobrenatural")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CacadorCriadorId");

                    b.ToTable("TB_SeresSobrenaturais", (string)null);
                });

            modelBuilder.Entity("ArquivoWinchester.Dominio.Entidades.CacadaEntidade.Cacada", b =>
                {
                    b.HasOne("ArquivoWinchester.Dominio.Entidades.CacadorEntidade.Cacador", "Cacador")
                        .WithMany("Cacadas")
                        .HasForeignKey("CacadorCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquivoWinchester.Dominio.Entidades.SerSobrenaturalEntidade.SerSobrenatural", "SerSobrenatural")
                        .WithMany("Cacadas")
                        .HasForeignKey("SerSobrenaturalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cacador");

                    b.Navigation("SerSobrenatural");
                });

            modelBuilder.Entity("ArquivoWinchester.Dominio.Entidades.SerSobrenaturalEntidade.SerSobrenatural", b =>
                {
                    b.HasOne("ArquivoWinchester.Dominio.Entidades.CacadorEntidade.Cacador", "Cacador")
                        .WithMany("SeresSobrenaturais")
                        .HasForeignKey("CacadorCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cacador");
                });

            modelBuilder.Entity("ArquivoWinchester.Dominio.Entidades.CacadorEntidade.Cacador", b =>
                {
                    b.Navigation("Cacadas");

                    b.Navigation("SeresSobrenaturais");
                });

            modelBuilder.Entity("ArquivoWinchester.Dominio.Entidades.SerSobrenaturalEntidade.SerSobrenatural", b =>
                {
                    b.Navigation("Cacadas");
                });
#pragma warning restore 612, 618
        }
    }
}
